class DepartmentNotFound(Exception): ...


class DepartmentCycleError(Exception): ...


class DepartmentNameConflict(Exception): ...


class ORMError(Exception): ...


class ORMIntegrityError(Exception): ...
