"""refactor employee reassignment on department deletion

Revision ID: 09d0289ba12f
Revises: f6f32cf8d041
Create Date: 2026-05-24 23:51:33.709548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d0289ba12f'
down_revision: Union[str, Sequence[str], None] = 'f6f32cf8d041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_department_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_department_id_fkey'), 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
