"""Add unique constraint for department name within parent

Revision ID: 5948857dac47
Revises: 3842eae66b62
Create Date: 2026-05-21 15:18:25.750617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5948857dac47'
down_revision: Union[str, Sequence[str], None] = '3842eae66b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name_within_parent_id', 'departments', ['name', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_within_parent_id', 'departments', type_='unique')
    # ### end Alembic commands ###
