"""Make Department.parent_id non-unique and indexed

Revision ID: 6d8e0f8ee308
Revises: 12fd0990c235
Create Date: 2026-05-18 22:47:05.906277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8e0f8ee308'
down_revision: Union[str, Sequence[str], None] = '12fd0990c235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_parent_id_key'), 'departments', type_='unique')
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.create_unique_constraint(op.f('departments_parent_id_key'), 'departments', ['parent_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
