"""add index unique root department name

Revision ID: 725980f72828
Revises: 09d0289ba12f
Create Date: 2026-05-25 01:13:24.172619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725980f72828'
down_revision: Union[str, Sequence[str], None] = '09d0289ba12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_root_department_name', 'departments', ['name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_root_department_name', table_name='departments', postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###
