"""Add ondelete=CASCADE to emploees FK

Revision ID: c355a0e5b43b
Revises: 725980f72828
Create Date: 2026-05-25 03:17:33.729605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c355a0e5b43b'
down_revision: Union[str, Sequence[str], None] = '725980f72828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_department_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_department_id_fkey'), 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
