"""make Employee.hired_at timezone-aware and nullable

Revision ID: f6f32cf8d041
Revises: 5948857dac47
Create Date: 2026-05-21 18:34:39.191447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f32cf8d041'
down_revision: Union[str, Sequence[str], None] = '5948857dac47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hired_at',
               existing_type=postgresql.TIMESTAMP(),
               existing_nullable=False,
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'hired_at',
               existing_type=sa.DateTime(timezone=True),
               existing_nullable=True,
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
